name: Install torch on macos-latest

on:
  workflow_dispatch:

jobs:
  install_torch:
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "macos-15"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Python-3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Print Python version
        shell: bash -l {0}
        run:  python --version
      - name: Print Python3 version
        shell: bash -l {0}
        run:  python3 --version
